# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nimat
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: auth
# "service" is the name of this project. This will also be added to your AWS resource names.
service: auth

provider:
  name: aws
  runtime: nodejs24.x
  region: us-east-1
  environment:
    CLIENT_ID: ${ssm:/CLIENT_ID}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:us-east-1:720180693865:table/Users
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  signup:
    handler: handlers/signUp.signUp
    events:
      - httpApi:
          path: /sign-up
          method: post
  confirm:
    handler: handlers/confirmSignUp.confirmSignUp
    events:
      - httpApi:
          path: /confirm
          method: post
  login:
    handler: handlers/signIn.signin
    events:
      - httpApi:
          path: /login
          method: post
  signout:
    handler: handlers/signOut.signOut
    events:
      - httpApi:
          path: /signout
          method: post
  forgotPassword:
    handler: handlers/forgotPassword.forgotPassword
    events:
      - httpApi:
          path: /forgot-password
          method: post
  confirmForgotPassword:
    handler: handlers/confirmForgotPassword.confirmForgotPassword
    events:
      - httpApi:
          path: /confirm-forgot-password
          method: post
